# Generated by Django 5.0.6 on 2024-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_linkedin_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='domains',
            field=models.ManyToManyField(to='profiles.domains'),
        ),
        migrations.AddField(
            model_name='project',
            name='domains',
            field=models.ManyToManyField(to='profiles.domains'),
        ),
    ]
